### ISSUE TITLE
2-way?

### ISSUE THREAD

**Issue by folofjc** [bsdz/google-drive-remarkable-sync#1]
Is this a 2-way sync? That is, does it download file changes from remarkable to google drive (as a form of backup) as well as move pdf files to the remarkable cloud?

**Comment by bsdz** [comment]
Currently this only works one way. You can change the parameter syncMode that can be either "update" or "mirror" with mirroring also deleting files from Remarkable device if not found in same location on Google Drive.

**Comment by folofjc** [comment]
Thanks!
