### ISSUE TITLE
Support for remarkable 2

### ISSUE THREAD

**Issue by leachim** [bsdz/google-drive-remarkable-sync#15]
Many thanks for this very useful script. 
I wonder if you have any experience in using the new remarkable 2 with this script? I get a 401 error when trying to set it up according to the instructions in the readme.

**Comment by bsdz** [comment]
Sadly I've only got a v1 device. That said, I expect the cloud storage API to be the same for v1 & v2. A 401 error sounds like an authentication issue. Perhaps you could try regenerating a rOneTimeCode?

**Comment by matuszeg** [comment]
Idk if this is still relevant but figured I'd share. I use this with my remarkable 2 and there have not been any problems.

**Comment by leachim** [comment]
I can confirm that it's working with remarkable 2.
