### ISSUE TITLE
Github doesn't know what license this is

### ISSUE THREAD

**Issue by Eeems** [bsdz/google-drive-remarkable-sync#16]
![License](https://shields.io/github/license/bsdz/google-drive-remarkable-sync)
Github doesn't seem to understand that this repo is under the MIT license. Perhaps the license file was modified enough that it's not working properly?

**Comment by bsdz** [comment]
Can confirm it's MIT license. Not sure why GitHub doesn't understand. Does it cause any problems?

**Comment by Eeems** [comment]
It means that if anything is trying to use a github shield like in my original comment, it will show as not identifiable. That and anything meant to use the Github metadata through one of their APIs will not recognize what license this is under.

**Comment by bsdz** [comment]
Is there an easy fix?

**Comment by Eeems** [comment]
I have no idea. Perhaps replacing the file with a fresh copy of the MIT license template?
https://github.com/licenses/license-templates/blob/master/templates/mit.txt

**Comment by bsdz** [comment]
Could be that. Just had a quick skim and found this https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#detecting-a-license so could because there are two license files.

**Comment by Eeems** [comment]
Oh, quite likely. In that case you might want to remove one of them.
