### ISSUE TITLE
Documentation mentions an option that isn't shown

### ISSUE THREAD

**Issue by leeuwerck** [bsdz/google-drive-remarkable-sync#18]
> In version drop down choose "Stable - include epub and shortcuts" Then press "Save" button.

![image](https://user-images.githubusercontent.com/1558602/112120706-d21b8c80-8bbe-11eb-9bad-159b6005dada.png)

**Comment by bsdz** [comment]
Looks like Google have introduced a new Apps Script UI and the new ui doesn't show the version descriptions. If you switch the the editor to legacy mode you'll see them:

![image](https://user-images.githubusercontent.com/6608130/112124062-dbeec100-8bb9-11eb-9ac4-cfe44be74804.png)

**Comment by leeuwerck** [comment]
Thanks!
