### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by NinjaOne** [bsdz/google-drive-remarkable-sync#20]
The script was previously running fine, but today I get this error message:

_______________
Exception: Request failed for https://document-storage-production-dot-remarkable-production.appspot.com returned code 401. Truncated server response: Serving request failed, Msg: invalid token: token contains an invalid number of segments: invalid token, Origin: invalid token: token contains an i... (use muteHttpExceptions option to examine full response)
listDocs	@ Remarkable.gs:110
Synchronizer	@ Synchronizer.gs:103
syncGoogleDriveWithRemarkableCloud	@ Library.gs:11
___________

 Apparrently something chaged in the routing. https://github.com/juruen/rmapi/issues/177

**Comment by oyvindlr** [comment]
Same error here. Used to work, but since 19th of May this shows up consistently.

**Comment by bsdz** [comment]
Indeed I am having the same issue. I'll try and investigate over the weekend.

**Comment by oyvindlr** [comment]
Check the link in @NinjaOne's post: https://github.com/juruen/rmapi/issues/177. Seems it has been fixed there already, but the error persists here.

**Comment by bsdz** [comment]
This should be resolved now. Update library to version 14 or copy code from github to your local appscript. Then run reset function() from README.md. Finally re-run sync with a new one time code.

**Comment by NinjaOne** [comment]
Everything works again! Thank you for quick response!
