### ISSUE TITLE
Exception: Request failed for https://document-storage-production-dot-remarkable-production.appspot.com returned code 401

### ISSUE THREAD

**Issue by franperr** [bsdz/google-drive-remarkable-sync#25]
Hi,
I installed the code in Google Script following the instructions (following option 1). I obtained from remarkable the one-time code at https://my.remarkable.com/device/mobile/connect and then when I execute the function run_sync, I have the following log:

```
15:11:07	Infos	Using existing Remarkable device id..
15:11:07	Infos	Using existing Remarkable device token..
15:11:08	Infos	Remarkable cloud storage host: document-storage-production-dot-remarkable-production.appspot.com
15:11:08	Infos	Fetching doc list from Remarkable cloud
15:11:08	Error	Exception: Request failed for https://document-storage-production-dot-remarkable-production.appspot.com returned code 401
listDocs	@ Remarkable.gs:113
Synchronizer	@ Synchronizer.gs:103
syncGoogleDriveWithRemarkableCloud	@ Library.gs:11

```

Any idea ? Thanks

**Comment by bsdz** [comment]
Not sure. Can you take a look at previous similar issues and see if suggestions there work for you? 

https://github.com/bsdz/google-drive-remarkable-sync/issues?q=is%3Aissue+document-storage-production-dot-remarkable-production.appspot.com+is%3Aclosed

**Comment by franperr** [comment]
Thank you for your fast answer. I checked issue #21, but I am already using the version 14 of the library RemarkableGoogleDriveSyncLib.
I also tried issue #20 : the reset function throws the same error 401, and after executing it, run_sync still gives the same error.

By the way, the path to get a one-time code from remarkable is now https://my.remarkable.com/device/mobile/connect instead of https://my.remarkable.com/device/connect/mobile

**Comment by bsdz** [comment]
The 401 error seems to suggest an authorisation issue. Beyond running the reset script I'm not sure what to suggest. It appears to be working for me so I don't think it's a global problem. That said, it's possible that you're part of a partial roll out to a new remarkable back end; although I've not heard of anything like that recently.

**Comment by franperr** [comment]
Thank you, I bought my remarkable on November 2021 and my connect subscription plan started on Nov 26th, maybe that could be the reason ?

I will try over the weekend to see if I can use the remarkable API directly, I will let you know.

**Comment by franperr** [comment]
I tried [rmapi](https://github.com/juruen/rmapi) and it worked, but I had the following warning:
`
WARNING!!!
  Using the new 1.5 sync, this has not been fully tested yet!!!
`
So I supposed it is a matter of API version

**Comment by bsdz** [comment]
Thanks for the additional info. I wasn't aware of the new protocol. At some point would be good to implement new "1.5 sync" api here (although has to be in a licence compatible manner - I think they are GPL and this project is MIT).

**Comment by koshibb** [comment]
So is there anything users can do that are being impacted by this?

**Comment by bsdz** [comment]
Short of enhancing the code base to encompass the new changes, nothing I'm aware of. Sorry

**Comment by saccentekennedy** [comment]
Just to say I'm affected by the same issue here too...
