### ISSUE TITLE
Does not work with Remarkable's new 1.5 storage API

### ISSUE THREAD

**Issue by DTBICT** [bsdz/google-drive-remarkable-sync#27]
Hi! It seems there is a problem. Since there has been some update on the Remarkable software the sync is not working anymore and I can't manage to reinstall it. Could you please help me? I've tried to reset the authentication credentials, but to no avail. I might be putting the code in the wrong place, since I am a beginner on github. Thank you for your support!

By the way, the link to get the code from Remarkable has changed to https://my.remarkable.com/device/mobile/connect
Some additional descriptions of the start of the sync with the remarkable would be really helpful, please!

- Paul

cf. screenshot for troubleshooting
<img width="1164" alt="Screenshot 2022-05-20 at 11 59 00" src="https://user-images.githubusercontent.com/105918160/169505168-287b889b-ab9b-499d-b7ce-b2605a0c2480.png">

**Comment by bsdz** [comment]
I'm not sure what's happening there. The message "deleted device" suggests perhaps the device has been removed from your account. If you go to https://my.remarkable.com/device/mobile/connect does it offer a new one-time-code?

**Comment by ctennenhouse** [comment]
Where does the authentication reset function go? The instructions say to paste it into code.gs. Should it go above or below run_sync()? I have tried both ways and reset the one-time auth code, but since yesterday I am still getting a 401 error.

**Comment by DTBICT** [comment]
Hi bsdz, I have tried to get a new one time code, and put it again into the code, but to no avail.
I also wonder where does the authentication reset function go, and what it's for.
Thanks for your patience with my learning!

By the way, I understand the code still works fine for you and your Google Drive Account?

**Comment by bsdz** [comment]
> Hi bsdz, I have tried to get a new one time code, and put it again into the code, but to no avail. I also wonder where does the authentication reset function go, and what it's for. Thanks for your patience with my learning!

If you paste the code into the same window you screenshotted earlier. The code can go above or below the existing run_sync function. Then change drop down to the reset function name and hit Run.

![image](https://user-images.githubusercontent.com/6608130/170493296-6e567273-984b-40b4-8ca9-6c52290a96c1.png)

> By the way, I understand the code still works fine for you and your Google Drive Account?

Yes it does although this might be because my device is fixed to an old API.

**Comment by DTBICT** [comment]
Ok I'll try within this week and let you know. I wish I could connect with an old api too!

**Comment by ridgetopfarms** [comment]
I am also experiencing an issue with this now.

**Comment by ridgetopfarms** [comment]
A quick work around was using the desktop remarkable app to sync a pdf over.

**Comment by bsdz** [comment]
I've started a [new branch](https://github.com/bsdz/google-drive-remarkable-sync/tree/remarkable_15_api) for integrating with Remarkable's new 1.5 api. It's incomplete and what's there has only been partially tested.
