### ISSUE TITLE
Error code 403. Truncated server response: Forbidden

### ISSUE THREAD

**Issue by romaindeveaud** [bsdz/google-drive-remarkable-sync#29]
Starting fromn July 22, I get the following error when executing the sync script that have been working flawlessly for over 1 year. I get the following error: 
<img width="1205" alt="Screenshot 2022-08-16 at 12 17 23" src="https://user-images.githubusercontent.com/128623/184856102-632216dd-8c3d-4711-90bb-cfd38ca8b481.png">

I tried to reset the one-time code and generate a new one, but it didn't change anything.
Did Remarkable change anything in their API or is it an issue with the google-drive-remarkable-sync library?

**Comment by bsdz** [comment]
Yes they've been switching people to a new API. See issue #27. You're one of the luckier ones. I started a new branch for the new API but stalled. In the meanwhile you try an alternative like rmapi combined with a local cache of your Google drive.
