### ISSUE TITLE
Syncs, but not quite

### ISSUE THREAD

**Issue by doomgutt** [bsdz/google-drive-remarkable-sync#3]
I've set up the device according to the manual, and it seems to have indeed connected as there is consistent synchronization between the drive and the tablet. The problem is that the synchronization isn't quite of the intended sort.

Having created the folders that are meant to sync with each other, their behavior is as follows:
- When Drive folder is empty but Remarkable folder has something in it, the sync deletes that files
- When Drive folder has a file but Remarkable folder is empty, the sync does nothing
- When there are files present in both folders, the Remarkable one is cleared, but the Drive files aren't synced

I suppose the conclusion is that Drive is somehow always perceived as empty, thus never syncing any files and deleting anything that's in the Remarkable folder?

Suggestions?
Thanks!

**Comment by bsdz** [comment]
Do yo have syncMode set to "mirror"? That might explain why some files are being deleted on your Remarkable.

Have you looked at the execution logs? That might help. 

Also files over 50MB are skipped. Remarkable doesn't support files greater than that size.

**Comment by doomgutt** [comment]
> Do yo have syncMode set to "mirror"? That might explain why some files are being deleted on your Remarkable.
> 
> 
> 
> Have you looked at the execution logs? That might help. 
> 
> 
> 
> Also files over 50MB are skipped. Remarkable doesn't support files greater than that size. 



Hey,

Yeah, I have it set to mirror, but it doesn’t mirror - it just deletes everything hehe. Might be worth trying it without mirror....

The logs say that it 
- finds 2 files in the google drive folder
- deletes everything that isn’t mirrored
- updates 0 documents
- quits

So, the mirroring seems to work well, just the transfer from GDrive to RM doesn’t.

The files are appropriately sized since I’ve opened them before on the tablet.

I’ll dig through the logs and whatever code that I can understand when I have a moment, and try to get it to work.

Thanks for the tips!

**Comment by bsdz** [comment]
There is another limitation. It only uploads PDFs currently. Not epubs. Take a look here:

https://github.com/bsdz/google-drive-remarkable-sync/blob/f82e9510ff80529cdc4e0f9d09c15589bb05815e/Synchronizer.js#L212

It wouldn't be difficult to include epubs. I'll do it in a later release.
