### ISSUE TITLE
Impossible to get one time code

### ISSUE THREAD

**Issue by guillaume-bzh** [bsdz/google-drive-remarkable-sync#30]
Hello,
It doesn't work since few month, and I think it's because my rOneTimeCode was expired, but I try to put a new one but always forbidden:
`Exception: Request failed for https://webapp-production-dot-remarkable-production.appspot.com returned code 403. Truncated server response: Forbidden
 (use muteHttpExceptions option to examine full response)` 
Have you the same problem ?
Guillaume

**Comment by bsdz** [comment]
I suspect you've been bitten by the backend API change. See this other issue #27 .
