### ISSUE TITLE
Paperpile, Google moving to hyperlinking

### ISSUE THREAD

**Issue by palvelin** [bsdz/google-drive-remarkable-sync#4]
(Related info: https://paperpile.com/blog/google-drive-sync-improvements/)
I've been trying to sync "Starred Papers" folder to Remarkable 2 now, but Paperpile has changed so that that folder only consists of links to original files. The nice sync script here does not work with links (i.e. can't fetch the original file).
Would be a great addition, if this could do that as well. I changed the folder structure in Paperpile to suit better Remarkable use and sync all Paperpile papers from Drive, but there will be a size issue soonish with that solution. Thus, "Starred Papers" would be great to have as an option.
I understand that Paperpile is just one use case, not close to so many hearts, but there should be many instances of services facing this new Google Policy, and thus affected users. Thanks for the script anyways!!

**Comment by bsdz** [comment]
From some [very light reading around this topic](https://gsuiteupdates.googleblog.com/2020/03/shortcuts-for-google-drive.html) it seems Google Drive no longer supports placing files in multiple places and use shortcuts instead (as of 30th Sept). Perhaps these shortcuts will have the special [MimeType SHORTCUT](https://developers.google.com/apps-script/reference/base/mime-type); if they do it might be worked into [generateZipBlob](https://github.com/bsdz/google-drive-remarkable-sync/blob/1ecc1e440e56ebf0fe296b95abb923a0ec79326b/Synchronizer.js#L140). This is only guessing as right now I don't think this affects me; so a low priority from my perspective. That said, I'm open to PRs that add this support (if accompanied with some instructions for manual testing). It would be a nice optional feature - to support following shortcuts.

**Comment by bsdz** [comment]
I've just uploaded an update that should follow shortcuts. Let me know if that also works for you.

**Comment by bsdz** [comment]
I think this issue is likely to be resolved now. I'll close it for now. Feel free to open another issue if it's not working for you.
