### ISSUE TITLE
ReferenceError: RemarkableGoogleDriveSyncLib is not defined (line 6, file "Code")

### ISSUE THREAD

**Issue by Seanmatthews** [bsdz/google-drive-remarkable-sync#5]
Received this error on a Remarkable 2 after following the instructions to manually copy the source files to my script project.

**Comment by bsdz** [comment]
Are you following Option 1 or Option 2?

**Comment by Seanmatthews** [comment]
> Are you following Option 1 or Option 2?

Option 2, copying the source files manually.

**Comment by bsdz** [comment]
If you're using in your own project (option 2) then you probably need to drop the alias "RemarkableGoogleDriveSyncLib". That is, in your run_sync() change "RemarkableGoogleDriveSyncLib.syncGoogleDriveWithRemarkableCloud" to just "syncGoogleDriveWithRemarkableCloud". I hope that helps.

**Comment by Seanmatthews** [comment]
Thanks, that solved it! Closing issue.
